# Generated by Django 5.0.5 on 2024-05-16 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('idade', models.IntegerField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quarto', models.CharField(max_length=50)),
            ],
        ),
    ]
