# Generated by Django 5.0.5 on 2024-05-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_reserva_quarto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
